version: '3'

services:
  taiko:
    build: .
    container_name: taiko-test
    environment:
        - TAIKO_BROWSER_ARGS=--no-sandbox,--start-maximized,--disable-dev-shm-usage
        - TAIKO_BROWSER_PATH=/usr/bin/google-chrome
        - TAIKO_SKIP_DOCUMENTATION=true
    volumes:
      - .:/taiko:rw
    command: sh -c "npm install && npm test"